In [255]:
import pandas as pd

df = pd.read_csv("../data/medicine_data.csv")

In [256]:
df.columns.tolist()

['product_id',
 'brand_name',
 'manufacturer',
 'price_inr',
 'is_discontinued',
 'dosage_form',
 'pack_size',
 'pack_unit',
 'num_active_ingredients',
 'primary_ingredient',
 'primary_strength',
 'active_ingredients',
 'therapeutic_class',
 'packaging_raw',
 'manufacturer_raw']

In [257]:
df.head()

,product_id,brand_name,manufacturer,price_inr,is_discontinued,dosage_form,pack_size,pack_unit,num_active_ingredients,primary_ingredient,primary_strength,active_ingredients,therapeutic_class,packaging_raw,manufacturer_raw
0,1,Augmentin 625 Duo Tablet,Glaxo SmithKline Pharmaceuticals Ltd,223.42,False,tablet,10.0,strip,2,Amoxycillin,500mg,"[{'name': 'Amoxycillin', 'strength': '500mg', ...",antibiotic,strip of 10 tablets,Glaxo SmithKline Pharmaceuticals Ltd
1,2,Azithral 500 Tablet,Alembic Pharmaceuticals Ltd,132.36,False,tablet,5.0,strip,1,Azithromycin,500mg,"[{'name': 'Azithromycin', 'strength': '500mg',...",antibiotic,strip of 5 tablets,Alembic Pharmaceuticals Ltd
2,3,Ascoril LS Syrup,Glenmark Pharmaceuticals Ltd,118.00,False,syrup,100.0,bottle,2,Ambroxol,30mg/5ml,"[{'name': 'Ambroxol', 'strength': '30mg/5ml', ...",bronchodilator,bottle of 100 ml Syrup,Glenmark Pharmaceuticals Ltd
3,4,Allegra 120mg Tablet,Sanofi India Ltd,218.81,False,tablet,10.0,strip,1,Fexofenadine,120mg,"[{'name': 'Fexofenadine', 'strength': '120mg',...",antihistamine,strip of 10 tablets,Sanofi India Ltd
4,5,Avil 25 Tablet,Sanofi India Ltd,10.96,False,tablet,15.0,strip,1,Pheniramine,25mg,"[{'name': 'Pheniramine', 'strength': '25mg', '...",other,strip of 15 tablets,Sanofi India Ltd

In [258]:
df.columns

Index(['product_id', 'brand_name', 'manufacturer', 'price_inr',
       'is_discontinued', 'dosage_form', 'pack_size', 'pack_unit',
       'num_active_ingredients', 'primary_ingredient', 'primary_strength',
       'active_ingredients', 'therapeutic_class', 'packaging_raw',
       'manufacturer_raw'],
      dtype='str')

In [259]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 253973 entries, 0 to 253972
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   product_id              253973 non-null  int64
 1   brand_name              253973 non-null  str
 2   manufacturer            253973 non-null  str
 3   price_inr               253973 non-null  float64
 4   is_discontinued         253973 non-null  bool
 5   dosage_form             253973 non-null  str
 6   pack_size               231643 non-null  float64
 7   pack_unit               231643 non-null  str
 8   num_active_ingredients  253973 non-null  int64
 9   primary_ingredient      253973 non-null  str
 10  primary_strength        228775 non-null  str
 11  active_ingredients      253973 non-null  str
 12  therapeutic_class       253973 non-null  str
 13  packaging_raw           253973 non-null  str
 14  manufacturer_raw        253973 non-null  str
dtypes: bool(1), float64(2), int64(2), str(10)
memory usage: 27.4 MB

In [260]:
df.isnull().sum()

product_id                    0
brand_name                    0
manufacturer                  0
price_inr                     0
is_discontinued               0
dosage_form                   0
pack_size                 22330
pack_unit                 22330
num_active_ingredients        0
primary_ingredient            0
primary_strength          25198
active_ingredients            0
therapeutic_class             0
packaging_raw                 0
manufacturer_raw              0
dtype: int64

In [261]:
df["price_inr"].describe()

count    253973.000000
mean        270.530844
std        3029.584134
min           0.000000
25%          48.000000
50%          79.000000
75%         140.000000
max      436000.000000
Name: price_inr, dtype: float64

In [262]:
df["active_ingredients"].head(10)

0    [{'name': 'Amoxycillin', 'strength': '500mg', ...
1    [{'name': 'Azithromycin', 'strength': '500mg',...
2    [{'name': 'Ambroxol', 'strength': '30mg/5ml', ...
3    [{'name': 'Fexofenadine', 'strength': '120mg',...
4    [{'name': 'Pheniramine', 'strength': '25mg', '...
5    [{'name': 'Montelukast', 'strength': '10mg', '...
6    [{'name': 'Amoxycillin', 'strength': '500mg', ...
7    [{'name': 'Azithromycin', 'strength': '500mg',...
8    [{'name': 'Hydroxyzine', 'strength': '25mg', '...
9    [{'name': 'Phenylephrine', 'strength': '5mg', ...
Name: active_ingredients, dtype: str

In [263]:
df["manufacturer"].head(10)

0    Glaxo SmithKline Pharmaceuticals Ltd
1             Alembic Pharmaceuticals Ltd
2            Glenmark Pharmaceuticals Ltd
3                        Sanofi India Ltd
4                        Sanofi India Ltd
5                        Sanofi India Ltd
6                                  Abbott
7                               Cipla Ltd
8             Dr Reddy's Laboratories Ltd
9            Glenmark Pharmaceuticals Ltd
Name: manufacturer, dtype: str

In [264]:
df.isnull().sum().sort_values(ascending=False)

primary_strength          25198
pack_unit                 22330
pack_size                 22330
manufacturer                  0
price_inr                     0
brand_name                    0
product_id                    0
dosage_form                   0
is_discontinued               0
num_active_ingredients        0
primary_ingredient            0
active_ingredients            0
therapeutic_class             0
packaging_raw                 0
manufacturer_raw              0
dtype: int64

In [265]:
# requiredColumns = [
#     "brand_name", 
#     "manufacturer", 
#     "price_inr",
#     "dosage_form", 
#     "pack_size",
#     "primary_ingredient",
#     "primary_strength",
#     "active_ingredients", 
#     "therapeutic_class"
# ]

# df = df[requiredColumns]

In [266]:
df.head()

,product_id,brand_name,manufacturer,price_inr,is_discontinued,dosage_form,pack_size,pack_unit,num_active_ingredients,primary_ingredient,primary_strength,active_ingredients,therapeutic_class,packaging_raw,manufacturer_raw
0,1,Augmentin 625 Duo Tablet,Glaxo SmithKline Pharmaceuticals Ltd,223.42,False,tablet,10.0,strip,2,Amoxycillin,500mg,"[{'name': 'Amoxycillin', 'strength': '500mg', ...",antibiotic,strip of 10 tablets,Glaxo SmithKline Pharmaceuticals Ltd
1,2,Azithral 500 Tablet,Alembic Pharmaceuticals Ltd,132.36,False,tablet,5.0,strip,1,Azithromycin,500mg,"[{'name': 'Azithromycin', 'strength': '500mg',...",antibiotic,strip of 5 tablets,Alembic Pharmaceuticals Ltd
2,3,Ascoril LS Syrup,Glenmark Pharmaceuticals Ltd,118.00,False,syrup,100.0,bottle,2,Ambroxol,30mg/5ml,"[{'name': 'Ambroxol', 'strength': '30mg/5ml', ...",bronchodilator,bottle of 100 ml Syrup,Glenmark Pharmaceuticals Ltd
3,4,Allegra 120mg Tablet,Sanofi India Ltd,218.81,False,tablet,10.0,strip,1,Fexofenadine,120mg,"[{'name': 'Fexofenadine', 'strength': '120mg',...",antihistamine,strip of 10 tablets,Sanofi India Ltd
4,5,Avil 25 Tablet,Sanofi India Ltd,10.96,False,tablet,15.0,strip,1,Pheniramine,25mg,"[{'name': 'Pheniramine', 'strength': '25mg', '...",other,strip of 15 tablets,Sanofi India Ltd

In [267]:
df["active_ingredients"].head(20)

0     [{'name': 'Amoxycillin', 'strength': '500mg', ...
1     [{'name': 'Azithromycin', 'strength': '500mg',...
2     [{'name': 'Ambroxol', 'strength': '30mg/5ml', ...
3     [{'name': 'Fexofenadine', 'strength': '120mg',...
4     [{'name': 'Pheniramine', 'strength': '25mg', '...
5     [{'name': 'Montelukast', 'strength': '10mg', '...
6     [{'name': 'Amoxycillin', 'strength': '500mg', ...
7     [{'name': 'Azithromycin', 'strength': '500mg',...
8     [{'name': 'Hydroxyzine', 'strength': '25mg', '...
9     [{'name': 'Phenylephrine', 'strength': '5mg', ...
10    [{'name': 'Ranitidine', 'strength': '150mg', '...
11    [{'name': 'Phenylephrine', 'strength': '5mg/5m...
12    [{'name': 'Phenylephrine', 'strength': None, '...
13    [{'name': 'Amoxycillin', 'strength': '200mg', ...
14    [{'name': 'Ambroxol', 'strength': '15mg/5ml', ...
15    [{'name': 'Clonidine', 'strength': None, 'full...
16    [{'name': 'Promethazine', 'strength': '25mg', ...
17    [{'name': 'Phenylephrine', 'strength': '5mg/5m...
18    [{'name': 'Fexofenadine', 'strength': '180mg',...
19    [{'name': 'Albendazole', 'strength': '400mg', ...
Name: active_ingredients, dtype: str

In [268]:
df["primary_ingredient"].head(20)

0       Amoxycillin
1      Azithromycin
2          Ambroxol
3      Fexofenadine
4       Pheniramine
5       Montelukast
6       Amoxycillin
7      Azithromycin
8       Hydroxyzine
9     Phenylephrine
10       Ranitidine
11    Phenylephrine
12    Phenylephrine
13      Amoxycillin
14         Ambroxol
15        Clonidine
16     Promethazine
17    Phenylephrine
18     Fexofenadine
19      Albendazole
Name: primary_ingredient, dtype: str

In [269]:
import ast

def clean_composition(text):
    if pd.isna(text):
        return ""

    try:
        ingredients = ast.literal_eval(text)

        result = []

        for ing in ingredients:
            name = str(ing.get("name") or "").strip().lower()
            strength = str(ing.get("strength") or "unknown").strip().lower()

            if not name:
                continue

            result.append(f"{name}_{strength}")

        result.sort()

        return " ".join(result)
    
    except (ValueError, SyntaxError, TypeError):
        return ""

In [ ]:
df["cleaned_composition"] = (
    df["active_ingredients"].apply(clean_composition)
)

In [271]:
(df["cleaned_composition"] == "").sum()

np.int64(0)

In [272]:
print("Empty compositions:", (df["cleaned_composition"] == "").sum())
print("Missing compositions:", df["cleaned_composition"].isna().sum())

Empty compositions: 0
Missing compositions: 0

In [273]:
df = df[df["price_inr"] > 0].copy()

In [274]:
len(df)

253969

In [275]:
df[
    [
        "active_ingredients",
        "cleaned_composition"
    ]
].head()

,active_ingredients,cleaned_composition
0,"[{'name': 'Amoxycillin', 'strength': '500mg', ...",amoxycillin_500mg clavulanic acid_125mg
1,"[{'name': 'Azithromycin', 'strength': '500mg',...",azithromycin_500mg
2,"[{'name': 'Ambroxol', 'strength': '30mg/5ml', ...",ambroxol_30mg/5ml levosalbutamol_1mg/5ml
3,"[{'name': 'Fexofenadine', 'strength': '120mg',...",fexofenadine_120mg
4,"[{'name': 'Pheniramine', 'strength': '25mg', '...",pheniramine_25mg

In [276]:
df["cleaned_composition"].value_counts().head(10)

cleaned_composition
aceclofenac_100mg paracetamol_325mg        4679
pantoprazole_40mg                          2643
domperidone_30mg rabeprazole_20mg          2617
amoxycillin_500mg clavulanic acid_125mg    2602
levocetirizine_5mg montelukast_10mg        2352
rabeprazole_20mg                           2101
ofloxacin_200mg ornidazole_500mg           2028
azithromycin_500mg                         1997
ofloxacin_200mg                            1988
glimepiride_2mg metformin_500mg            1819
Name: count, dtype: int64

In [277]:
def find_alternatives(medicineName):
    
    medicine = df[
        df["brand_name"].str.lower() == medicineName.lower()
    ]

    if medicine.empty:
        print("Medicine not found.")
        return None

    composition = medicine.iloc[0]["cleaned_composition"]

    alternatives = df[
        df["cleaned_composition"] == composition
    ]

    alternatives = alternatives.sort_values(by="price_inr")

    return alternatives[
        [
            "brand_name",
            "manufacturer",
            "price_inr"
        ]
    ]

In [278]:
df["brand_name"].head(20)

0            Augmentin 625 Duo Tablet
1                 Azithral 500 Tablet
2                    Ascoril LS Syrup
3                Allegra 120mg Tablet
4                      Avil 25 Tablet
5                    Allegra-M Tablet
6                Amoxyclav 625 Tablet
7                     Azee 500 Tablet
8                  Atarax 25mg Tablet
9     Ascoril D Plus Syrup Sugar Free
10                  Aciloc 150 Tablet
11                         Alex Syrup
12                      Anovate Cream
13      Augmentin Duo Oral Suspension
14                   Ambrodil-S Syrup
15                     Arkamin Tablet
16                     Avomine Tablet
17      Asthakind-DX Syrup Sugar Free
18               Allegra 180mg Tablet
19           Albendazole 400mg Tablet
Name: brand_name, dtype: str

In [279]:
find_alternatives("Azee 500 Tablet")

,brand_name,manufacturer,price_inr
220187,TN 500 Tablet,Vhb Life Sciences Inc,11.02
252243,Zithnu 500mg Tablet,Genesis Biotech Inc,15.00
249164,Zycin 500mg Injection,Zydus Cadila,15.62
5802,Azileo 500mg Tablet,Leo Pharmaceuticals,17.32
110931,Izamed 500mg Tablet,Medoz Pharmaceutical Pvt. Ltd,18.70
...,...,...,...
15998,Azolide RD 500mg Capsule,J.K. Drugs & Pharmaceutical Pvt Ltd,500.00
16199,Azotox 500mg Tablet,Biocare Remedies,594.00
6947,Aztel 500mg Tablet,Artel Laboratories,630.00
154454,Nizith 500mg Tablet,Novus Life Sciences Pvt Ltd,650.00
99661,Gith 500mg Tablet,GR Healthcare Laboratories,748.50

In [280]:
df["price_inr"].describe()

count    253969.000000
mean        270.535105
std        3029.607802
min           1.050000
25%          48.000000
50%          79.000000
75%         140.000000
max      436000.000000
Name: price_inr, dtype: float64

In [281]:
(df["price_inr"] <= 0).sum()

np.int64(0)

In [282]:
(df["cleaned_composition"] == "").sum()

np.int64(0)

In [283]:
df["cleaned_composition"].isna().sum()

np.int64(0)

In [284]:
features = [
    "dosage_form",
    "pack_size",
    "pack_unit",
    "primary_ingredient",
    "primary_strength",
    "therapeutic_class",
    "clean_composition"
]

target = "price_inr"

X = df[features]
y = df[target]

KeyError: "['clean_composition'] not in index"

In [ ]:
X.isnull().sum()

dosage_form               0
pack_size             22330
primary_ingredient        0
primary_strength      25194
therapeutic_class         0
dtype: int64

In [ ]:
X.dtypes

dosage_form               str
pack_size             float64
primary_ingredient        str
primary_strength          str
therapeutic_class         str
dtype: object

In [ ]:
print("Empty compositions:", (df["cleaned_composition"] == "").sum())
print("Missing compositions:", df["cleaned_composition"].isna().sum())

Empty compositions: 0
Missing compositions: 0

In [ ]:
df = df[df["price_inr"] > 0].copy()

In [ ]:
df["price_inr"].quantile(
    [0.90, 0.95, 0.99, 0.995, 0.999]
)

0.900      254.0000
0.950      430.5000
0.990     2899.3200
0.995     6740.6572
0.999    26593.5200
Name: price_inr, dtype: float64

In [ ]:
df[
    [
        "brand_name",
        "manufacturer",
        "price_inr",
        "dosage_form",
        "primary_ingredient"
    ]
].sort_values(
    "price_inr",
    ascending=False
).head(20)

,brand_name,manufacturer,price_inr,dosage_form,primary_ingredient
113862,Imbruvica 140mg Capsule,Janssen Pharmaceuticals,436000.00,capsule,Ibrutinib
217021,Tecentriq 1200mg Injection,Roche Products India Pvt Ltd,396725.00,solution,Atezolizumab
243971,Xtandi 40mg Soft Capsule,Astellas Pharma Inc,335635.00,capsule,Enzalutamide
28711,Besponsa 1mg Injection,Pfizer Ltd,330000.00,injection,Inotuzumab Ozogamacin
113861,Imbruvica 140mg Capsule,Janssen Pharmaceuticals,328000.00,capsule,Ibrutinib
129170,Lorbriqua 100mg Tablet,Pfizer Ltd,312000.00,tablet,Lorlatinib
219482,Tecentriq Injection,Roche Products India Pvt Ltd,277708.00,injection,Atezolizumab
35994,Cyramza 500mg Injection,Eli Lilly and Company India Pvt Ltd,257532.00,injection,Ramucirumab
175276,Perjeta 420mg Injection,Roche Products India Pvt Ltd,255150.00,injection,Pertuzumab
116435,Kadcyla 160mg Injection,Roche Products India Pvt Ltd,248937.00,injection,Ado-trastuzumab emtansine
115726,Keytruda Injection,MSD Pharmaceuticals Pvt Ltd,236500.00,injection,Pembrolizumab
201951,Sprycel 70mg Tablet,BMS India Pvt Ltd,211538.51,tablet,Dasatinib
215283,Tagrisso 80mg Tablet,AstraZeneca,204435.84,tablet,Osimertinib
219061,Tagrisso 40mg Tablet,AstraZeneca,202391.48,tablet,Osimertinib
200643,Sprycel 50mg Tablet,BMS India Pvt Ltd,197238.10,tablet,Dasatinib
108523,Imfinzi Injection,AstraZeneca,189585.00,injection,Durvalumab
58222,Calquence 100mg Capsule,AstraZeneca,181765.00,capsule,Acalabrutinib
10844,Arzerra 1000mg Solution for Infusion,Glaxo SmithKline Pharmaceuticals Ltd,168520.00,solution,Ofatumumab
180605,Pamiglan 500mg Injection,Gland Pharma Limited,156451.30,injection,Pemetrexed
116327,Kadcyla 100mg Injection,Roche Products India Pvt Ltd,155585.00,injection,Ado-trastuzumab emtansine

In [ ]:
df.columns

Index(['brand_name', 'manufacturer', 'price_inr', 'dosage_form', 'pack_size',
       'primary_ingredient', 'primary_strength', 'active_ingredients',
       'therapeutic_class', 'cleaned_composition'],
      dtype='str')

In [ ]:
df["price_inr"].sort_values(
    ascending=False
).head(20)

113862    436000.00
217021    396725.00
243971    335635.00
28711     330000.00
113861    328000.00
129170    312000.00
219482    277708.00
35994     257532.00
175276    255150.00
116435    248937.00
115726    236500.00
201951    211538.51
215283    204435.84
219061    202391.48
200643    197238.10
108523    189585.00
58222     181765.00
10844     168520.00
180605    156451.30
116327    155585.00
Name: price_inr, dtype: float64

In [ ]:
df[features].nunique()

dosage_form             15
pack_size               91
primary_ingredient    1582
primary_strength       673
therapeutic_class       11
dtype: int64

In [ ]:
df["dosage_form"].value_counts().head(15)

dosage_form
tablet        152586
injection      32040
capsule        22265
syrup          16747
suspension      9179
drops           5282
cream           5071
other           4503
solution        1808
gel             1687
ointment        1669
powder           377
spray            366
inhaler          267
respules         122
Name: count, dtype: int64

In [ ]:
df["therapeutic_class"].value_counts().head(15)

therapeutic_class
other               144115
antibiotic           30660
analgesic            24105
antacid              17432
antihistamine        13414
antidiabetic          8957
antihypertensive      7324
corticosteroid        2968
antidepressant        2499
bronchodilator        1802
diuretic               693
Name: count, dtype: int64

In [ ]:
df["pack_size"].value_counts().head(20)

pack_size
10.0     155076
30.0      12281
15.0       9525
100.0      8334
60.0       7719
5.0        6460
6.0        6273
1.0        5231
2.0        5075
4.0        3431
3.0        2568
20.0       2067
200.0      1868
50.0        902
170.0       821
7.0         743
14.0        683
75.0        592
25.0        243
8.0         202
Name: count, dtype: int64

In [ ]:
df["pack_size"].describe()

count    231639.000000
mean         18.989091
std          36.717597
min           1.000000
25%          10.000000
50%          10.000000
75%          10.000000
max        5000.000000
Name: pack_size, dtype: float64

In [ ]:
df["cleaned_composition"].nunique()

9912

In [ ]:
features = [
    "dosage_form",
    "pack_size",
    "pack_unit",
    "primary_ingredient",
    "primary_strength",
    "therapeutic_class",
    "num_active_ingredients"
]

target = "price_inr"

X = df[features]
y = df[target]

In [ ]:
df.columns.tolist()

['brand_name',
 'manufacturer',
 'price_inr',
 'dosage_form',
 'pack_size',
 'primary_ingredient',
 'primary_strength',
 'active_ingredients',
 'therapeutic_class',
 'cleaned_composition']

In [285]:
X.dtypes

dosage_form                   str
pack_size                 float64
pack_unit                     str
primary_ingredient            str
primary_strength              str
therapeutic_class             str
num_active_ingredients      int64
dtype: object

In [286]:
X.isnull().sum()

dosage_form                   0
pack_size                 22330
pack_unit                 22330
primary_ingredient            0
primary_strength          25194
therapeutic_class             0
num_active_ingredients        0
dtype: int64

In [287]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
num_features = [
    "pack_size",
    "num_active_ingredients"
]

categorical_features = [
    "dosage_form",
    "pack_unit",
    "primary_ingredient",
    "primary_strength",
    "therapeutic_class"
]